import { createRng, hashString, type Rng } from '@/core/utils/rng';
import type { PuzzleMode } from './types';

/* --------------------------------------------------------- Blackout --- */

export const LIGHTS_SIZE = 5;

export function lightsNeighbours(i: number): number[] {
  const n = LIGHTS_SIZE;
  const r = Math.floor(i / n);
  const c = i % n;
  const out = [i];
  if (r > 0) out.push(i - n);
  if (r < n - 1) out.push(i + n);
  if (c > 0) out.push(i - 1);
  if (c < n - 1) out.push(i + 1);
  return out;
}

/**
 * Generated by applying random *legal moves* to a solved board, which
 * guarantees solvability — the classic mistake with Lights Out is shuffling
 * cells directly and producing an unsolvable position.
 */
export function makeLights(rng: Rng, difficulty: number): boolean[] {
  const cells = new Array(LIGHTS_SIZE * LIGHTS_SIZE).fill(false);
  const moves = 4 + Math.floor(rng() * (4 + difficulty * 6));
  for (let m = 0; m < moves; m++) {
    const i = Math.floor(rng() * cells.length);
    for (const j of lightsNeighbours(i)) cells[j] = !cells[j];
  }
  // A board that starts solved is not a puzzle.
  if (cells.every((c) => !c)) cells[Math.floor(rng() * cells.length)] = true;
  return cells;
}

export const lightsSolved = (cells: boolean[]) => cells.every((c) => !c);

/* ---------------------------------------------------------- Shuffle --- */

export const SLIDE_SIZE = 3;

export function makeSlide(rng: Rng, difficulty: number): number[] {
  const n = SLIDE_SIZE * SLIDE_SIZE;
  const tiles = Array.from({ length: n }, (_, i) => (i + 1) % n); // 0 = empty
  let empty = n - 1;
  const shuffles = 40 + Math.floor(difficulty * 60);
  for (let s = 0; s < shuffles; s++) {
    const options = slideNeighbours(empty);
    const pick = options[Math.floor(rng() * options.length)];
    tiles[empty] = tiles[pick];
    tiles[pick] = 0;
    empty = pick;
  }
  if (slideSolved(tiles)) return makeSlide(rng, difficulty + 1);
  return tiles;
}

export function slideNeighbours(i: number): number[] {
  const n = SLIDE_SIZE;
  const r = Math.floor(i / n);
  const c = i % n;
  const out: number[] = [];
  if (r > 0) out.push(i - n);
  if (r < n - 1) out.push(i + n);
  if (c > 0) out.push(i - 1);
  if (c < n - 1) out.push(i + 1);
  return out;
}

export function slideSolved(tiles: number[]): boolean {
  for (let i = 0; i < tiles.length - 1; i++) if (tiles[i] !== i + 1) return false;
  return tiles[tiles.length - 1] === 0;
}

/* ------------------------------------------------------------- Echo --- */

export const MEMORY_PADS = 6;

export function makeMemorySequence(rng: Rng, length: number): number[] {
  return Array.from({ length }, () => Math.floor(rng() * MEMORY_PADS));
}

/* ------------------------------------------------------------ daily --- */

/**
 * The daily puzzle is a pure function of the date, so every device produces the
 * same board without any network — and it cannot be rerolled by restarting.
 */
export function dailyFor(dayKey: string): { mode: PuzzleMode; seed: number; difficulty: number } {
  const h = hashString(`pocketverse-daily-${dayKey}`);
  const rng = createRng(h);
  const modes: PuzzleMode[] = ['lights', 'slide', 'memory'];
  return {
    mode: modes[Math.floor(rng() * modes.length)],
    seed: h,
    difficulty: 1 + Math.floor(rng() * 3),
  };
}
